"""
Unified Snakemake workflow to pull the required resources and build required
indices all in one go.
"""

import os
import sys
import yaml
import pandas as pd
import datetime
from snakemake.utils import min_version, validate

# Needs to be at least this for apptainer path bindings to work as we need them.
min_version("9.20.0")
timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")


configfile: workflow.source_path("../config/container_config.yaml")


gencode_or_ucsc = None
gencode2ensembl_file = "resources/gencode2ensembl_human.tsv"
ucsc_genome_build = "hg38"
ENSEMBL_ORGANISM = "homo_sapiens"


validate(config, workflow.source_path("schemas/config.schema.yaml"))

# check if genome build is supported
if config["genome_build"] not in ["GRCh38", "GRCm38", "GRCm39"]:
    sys.exit(f"Genome build {config['genome_build']} not supported.")

# set mouse specific variables
if config["organism"] == "mouse":
    gencode_or_ucsc = "gencode" if config["genome_build"] < "GRCm39" else "UCSC"
    ucsc_genome_build = "mm39" if config["genome_build"] == "GRCm39" else "mm10"
    gencode2ensembl_file = "resources/gencode2ensembl_mouse.tsv"
    ENSEMBL_ORGANISM = "mus_musculus"


# translate the gencode version to ensembl version for ensembl specific resources
gencode2ensembl = pd.read_csv(
    workflow.source_path(gencode2ensembl_file), sep="\t", dtype=str
)

ENSEMBL_VERSION = gencode2ensembl[
    gencode2ensembl.GENCODE_release == config["release"]
].Ensembl_release.values[0]

ENSEMBL_ASSEMBLY_BUILD = (
    gencode2ensembl[gencode2ensembl.GENCODE_release == config["release"]]
    .Genome_assembly_version.values[0]
    .removeprefix("GRCh")
    .removeprefix("GRCm")
)

GENCODE2ENSEMBL_CHROM_MAPPING = workflow.source_path(
    "resources/GRCh38_ensembl2gencode.txt"
)
MINIMAL_GNOMAD_HEADER_FILE = workflow.source_path("resources/minimal_gnomad_header.txt")
TCGA_VIRUS_FILE = workflow.source_path("resources/tcga_viruses.tsv")
PA_REGION_BED_PATH = workflow.source_path(
    "resources/GRCh38_pseudoautosomal_regions.bed"
)


# For both sections.
include: "rules/common.smk"
include: "rules/sequence_dict.smk"
# For pulling resources.
include: "rules/intervals.smk"
include: "rules/faidx.smk"
include: "rules/prepare_ucsc.smk"
include: "rules/genome_masking.smk"
include: "rules/pull_resources.smk"
include: "rules/build_indices.smk"
include: "rules/uniprot_annotations.smk"
# For building indices.
include: "rules/bwa-mem.smk"
include: "rules/bwa-mem2.smk"
include: "rules/star.smk"
include: "rules/bowtie2.smk"
include: "rules/salmon.smk"
include: "rules/kallisto.smk"
include: "rules/snpeff.smk"
include: "rules/transcript_annotation.smk"
include: "rules/hisat2.smk"


onstart:
    # write the config to the output directory for reproducibility
    if not os.path.exists("configs"):
        os.mkdir("configs")
    with open(f"configs/{timestamp}_pull_resources_config.yaml", "w") as configfile:
        yaml.dump(config, configfile, default_flow_style=False)


rule all:
    default_target: True
    input:
        resources=get_pull_resources_output,
        indices=get_build_indices_output,
