name: tronmake_genome_lib_builder
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  # Ensure compatability with requests. Else there may be
  # errors along the lines of UNEXPECTED_EOF_WHILE_READING
  # from SSL.
  - conda-forge::openssl<=3.4.2
  - conda-forge::make
  - conda-forge::eido
  - conda-forge::peppy
  - conda-forge::pytest-workflow
  - conda-forge::mkdocs
  - conda-forge::mkdocs-material
  - conda-forge::mkdocs-table-reader-plugin
  - bioconda::snakemake-minimal=9.13.7 # pin this exact version as later relative paths are bound in apptainer (can be unpinned as soon as https://github.com/snakemake/snakemake/pull/4142 is merged)
  - bioconda::snakemake-storage-plugin-http
  - bioconda::snakemake-executor-plugin-cluster-generic
