[workspace]
authors = [
  "Jonas Freimuth <jonas.freimuth@tron-mainz.de>",
  "Johannes Hausmann <johannes.hausmann@tron-mainz.de>",
  "Luis Kress <luis.kress@tron-mainz.de>"
]
channels = ["conda-forge", "bioconda"]
description = "Reproducible generation of references and resources for next generation sequencing pipelines."
name = "tronmake-genome-lib-builder"
platforms = ["linux-64"]
version = "0.0.3"

[dependencies]
openssl = { version = "<=3.4.2", channel = "conda-forge" }
eido = { channel = "conda-forge" }
peppy = { channel = "conda-forge" }
snakemake-minimal = { version = "9.13.7.*", channel = "bioconda" }
snakemake-storage-plugin-http = { channel = "bioconda" }
snakemake-executor-plugin-cluster-generic = { channel = "bioconda" }

[feature.docs.dependencies]
mkdocs = { channel = "conda-forge" }
mkdocs-material = { channel = "conda-forge" }
mkdocs-table-reader-plugin = { channel = "conda-forge" }

[feature.docs.tasks]
documentation = "mkdocs build -f docs/tronmake-genome-lib-builder/mkdocs.yml"

[feature.test.dependencies]
pytest-workflow = { channel = "conda-forge" }

[feature.test.tasks]
unittest = "pytest --tag unittest"

[feature.style-md.dependencies]
mdformat = ">=0.7.22,<0.8"
mdformat-gfm = ">=1.0.0,<2"
mdformat-shfmt = ">=0.2.0,<0.3"
mdformat-tables = ">=1.0.0,<2"

[feature.style-md.tasks]
style-md = { cmd = "mdformat **/*.md", default-environment = "style-md" }
lint-md = { cmd = "mdformat --check **/*.md", default-environment = "style-md" }

[feature.style-python.dependencies]
black = ">=26.3.1,<27"

[feature.style-python.tasks]
style-python = { cmd = "black **/*.py", default-environment = "style-python" }
lint-python = { cmd = "black --check **/*.py", default-environment = "style-python" }

[feature.style-snakemake.dependencies]
snakefmt = ">=1.1.0,<2"

[feature.style-snakemake.tasks]
style-snakemake = { cmd = "snakefmt workflow/", default-environment = "style-snakemake" }
lint-snakemake = { cmd = "snakefmt --check workflow/", default-environment = "style-snakemake" }

[feature.style-toml.dependencies]
tombi = ">=0.10.5,<0.11"

[feature.style-toml.tasks]
style-toml = { cmd = "tombi format **/*.toml", default-environment = "style-toml" }
lint-toml = { cmd = "tombi format --check **/*.toml", default-environment = "style-toml" }

[feature.style-yaml.dependencies]
yamlfmt = ">=0.21.0,<0.22"

[feature.style-yaml.tasks]
style-yaml = { cmd = "yamlfmt **/*.yaml **/*.yml", default-environment = "style-yaml" }
lint-yaml = { cmd = "yamlfmt -lint **/*.yaml **/*.yml", default-environment = "style-yaml" }

[environments]
docs = { features = ["docs"], no-default-feature = true }
test = { features = ["test"] }
style-md = { features = ["style-md"], no-default-feature = true }
style-python = { features = ["style-python"], no-default-feature = true }
style-snakemake = { features = ["style-snakemake"], no-default-feature = true }
style-toml = { features = ["style-toml"], no-default-feature = true }
style-yaml = { features = ["style-yaml"], no-default-feature = true }

[tasks]
# Order matters, these are laid out from most likely to fail during develompent
# to least likely.
style = { depends-on = [
  "style-snakemake",
  "style-python",
  "style-md",
  "style-yaml",
  "style-toml"
] }
lint = { depends-on = [
  "lint-snakemake",
  "lint-python",
  "lint-md",
  "lint-yaml",
  "lint-toml"
] }
