organism: human
release: "46"
genome-build: GRCh38

# this has to be true, if the indices are built for a testexample
# the line can be removed in case of a normal sized genome
minigenome: false

# adds the defined slop to the generic exome definition
intron-slop: 20 

# Paramter for STAR index creation. Adapt to the read size f necessary
star-sjdb-overhang: 100

GENCODE_URL: "https://ftp.ebi.ac.uk/pub/databases/gencode"
UCSC_URL: "https://hgdownload.soe.ucsc.edu/gbdb/hg38"
UCSC_GOLDEN_PATH_URL: "https://hgdownload.soe.ucsc.edu/goldenPath"
GATK_URL: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0"
