organism: human
release: "46"
genome-build: GRCh38
gnomad-release: 4.1

# adds the defined slop to the generic exome definition (+/- intron-slop bp of intronic sequence)
intron-slop: 20

# Paramter for STAR index creation. Adapt to the read size if necessary
star-sjdb-overhang: 100
star-genome-sa-index-n-bases: 14 # see STAR parameter genomeSAindexNbases

# Remove variants from gnomad VCF with poplutation allele frequency <= this cutoff
minimum_allele_frequency: 0.001

# GENCODE transcript definition for exome bed (pre v48 basic after v48 basic or GENCODE_Primary)
exome_transcript_definition: "basic"

GENCODE_URL: "https://ftp.ebi.ac.uk/pub/databases/gencode"
UCSC_URL: "https://hgdownload.soe.ucsc.edu/gbdb/hg38"
UCSC_GOLDEN_PATH_URL: "https://hgdownload.soe.ucsc.edu/goldenPath"
GATK_URL: "https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0"
GNOMAD_URL: "https://storage.googleapis.com/gcp-public-data--gnomad/release"

chrom-filter:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY
