#!/usr/bin/env bash
set -euo pipefail

# This script generates a Sarek-compatible nextflow.config file that points to
# the reference and resource files generated by OBLX.
# The config provided runs Sarek with Mutect2 and SnpEff based on bwa-mem2
# alignments. The config is intended to be used for WES data but can be modified
# as needed for other data types or tools.

# Usage:
#   ./write_sarek_config.sh /path/to/oblx_library /path/to/output/nextflow.config

OBLX_LIBRARY_DIR="${1:-}"
OUT_CONFIG="${2:-nextflow.config}"

if [[ -z "${OBLX_LIBRARY_DIR}" ]]; then
    echo "Usage: $0 /path/to/oblx_library [/path/to/output/nextflow.config]" >&2
    exit 1
fi

snpeff_db="$(grep .genome "${OBLX_LIBRARY_DIR}"/indices/snpeff/snpeff.config | cut -d ' ' -f3 | tr -d '\n')"

cat >"${OUT_CONFIG}" <<EOF
params {
    // General setup
    igenomes_ignore = true

    // Point Sarek at the OBLX-generated reference
    fasta       = '${OBLX_LIBRARY_DIR}/resources/ref_genome.fasta'
    fasta_fai         = '${OBLX_LIBRARY_DIR}/resources/ref_genome.fasta.fai'
    dict        = '${OBLX_LIBRARY_DIR}/resources/ref_genome.dict'
    cf_chrom_len = '${OBLX_LIBRARY_DIR}/resources/ref_genome.fasta.fai'

    // Point to bwa-mem2 reference index
    aligner     = 'bwa-mem2'
    bwamem2     = '${OBLX_LIBRARY_DIR}/indices/bwa_mem2/'

    // Setup WES analysis parameters
    wes       = true
    intervals = '${OBLX_LIBRARY_DIR}/resources/exome_definition/ref_exome.bed'

    // Germline variant resources
    germline_resource     = '${OBLX_LIBRARY_DIR}/resources/germline_variants/af_only_gnomad_hg38.vcf.gz'
    germline_resource_tbi = '${OBLX_LIBRARY_DIR}/resources/germline_variants/af_only_gnomad_hg38.vcf.gz.tbi'
    dbsnp                 = '${OBLX_LIBRARY_DIR}/resources/germline_variants/dbSNP_151.vcf.gz'
    dbsnp_tbi             = '${OBLX_LIBRARY_DIR}/resources/germline_variants/dbSNP_151.vcf.gz.tbi'
    known_snps            = '${OBLX_LIBRARY_DIR}/resources/gatk_bundle/1000G_omni2.5.hg38.vcf.gz'
    known_snps_tbi        = '${OBLX_LIBRARY_DIR}/resources/gatk_bundle/1000G_omni2.5.hg38.vcf.gz.tbi'
    known_indels          = '${OBLX_LIBRARY_DIR}/resources/gatk_bundle/Homo_sapiens_assembly38.known_indels.vcf.gz'
    known_indels_tbi      = '${OBLX_LIBRARY_DIR}/resources/gatk_bundle/Homo_sapiens_assembly38.known_indels.vcf.gz.tbi'
    mills                 = '${OBLX_LIBRARY_DIR}/resources/gatk_bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz'
    mills_tbi             = '${OBLX_LIBRARY_DIR}/resources/gatk_bundle/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi'
    
    // SnpEff annotator specification
    download_cache   = false
    snpeff_cache     = '${OBLX_LIBRARY_DIR}/indices/snpeff/data/'
    snpeff_db        = '${snpeff_db}'
}

process {
  withName: 'SNPEFF_SNPEFF' {
      ext.args = '-c ${OBLX_LIBRARY_DIR}/indices/snpeff/snpeff.config'
  }
}


EOF

echo "Wrote ${OUT_CONFIG}"
