site_name: OBLX
nav:
  - "OBLX: Omics builder for Bioinformatics resource Libraries and indeXes": index.md
  - Download Resources: pull_resources.md
  - Build Indices: build_indices.md
  - Configuration: configuration.md
  - Supported Tools: supported_tools.md
  - Developer Guide: developer_guide.md
theme:
  name: material
  logo: resources/logo.png
  features:
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

copyright: © TRON gGmbH, 2026. This work is licensed under MIT.

plugins:
  - search
  - table-reader
