name: Continuous integration tasks
on: [push]

jobs:
  unit_tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - run: |
          git submodule update
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          init-shell: bash
          # Ensure issues with the channel priority in the pipeline environment
          # are caught.
          condarc: |
            channel_priority: strict
          post-cleanup: "none"
      - run: |
          make unittest
        shell: bash -el {0}
